# coding: utf-8

"""
    Kubeflow Trainer OpenAPI Spec

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: unversioned
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TrainerV1alpha1CheckpointInfo(BaseModel):
    """
    CheckpointInfo represents information about a specific checkpoint.
    """ # noqa: E501
    created_at: datetime = Field(description="Timestamp when the checkpoint was created.", alias="createdAt")
    epoch: Optional[StrictInt] = Field(default=None, description="Epoch number when the checkpoint was created.")
    metrics: Optional[Dict[str, StrictStr]] = Field(default=None, description="Training metrics at the time of checkpoint creation.")
    path: StrictStr = Field(description="Path or URI of the checkpoint.")
    size: Optional[StrictInt] = Field(default=None, description="Size of the checkpoint (in bytes).")
    step: Optional[StrictInt] = Field(default=None, description="Step number when the checkpoint was created.")
    __properties: ClassVar[List[str]] = ["createdAt", "epoch", "metrics", "path", "size", "step"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrainerV1alpha1CheckpointInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrainerV1alpha1CheckpointInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdAt": obj.get("createdAt"),
            "epoch": obj.get("epoch"),
            "metrics": obj.get("metrics"),
            "path": obj.get("path") if obj.get("path") is not None else '',
            "size": obj.get("size"),
            "step": obj.get("step")
        })
        return _obj


