apiVersion: trainer.kubeflow.org/v1alpha1
kind: ClusterTrainingRuntime
metadata:
  name: torch-cuda-2-4-1
  labels:
    trainer.kubeflow.org/framework: torch
spec:
  mlPolicy:
    numNodes: 2
    torch:
      numProcPerNode: 1
  template:
    spec:
      replicatedJobs:
        - name: node
          template:
            metadata:
              labels:
                trainer.kubeflow.org/trainjob-ancestor-step: trainer
            spec:
              template:
                spec:
                  terminationGracePeriodSeconds: 120
                  containers:
                    - name: node
                      image: quay.io/modh/training:py311-cuda121-torch241
                      command:
                        - bash
                        - -c
                      env:
                        - name: HF_HOME
                          value: /mnt/shared/.cache
                        - name: NCCL_DEBUG
                          value: INFO
                      resources:
                        limits:
                          cpu: "2"
                          memory: 24Gi
                        requests:
                          cpu: "2"
                          memory: 20Gi
