# Copyright The Kubeflow Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: training-hub-universal-cuda
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/opendatahub-io/distributed-workloads/tree/main/images/universal/training"
    opendatahub.io/notebook-image-name: "Training | Jupyter | PyTorch | CUDA | Python"
    opendatahub.io/notebook-image-desc: "Training runtime image for CUDA GPU-based fine-tuning and distributed training."
    opendatahub.io/notebook-image-order: "2"
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: "3.4"
      annotations:
        opendatahub.io/workbench-image-recommended: 'false'
        opendatahub.io/notebook-build-commit: a66ec72
        opendatahub.io/notebook-software: |
          [
            {"name": "CUDA", "version": "13.0"},
            {"name": "Python", "version": "v3.12"},
            {"name": "PyTorch", "version": "2.10.0"},
            {"name": "Training Hub", "version": "v0.6.0"}
          ]
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "transformers", "version": "4.57.6"},
            {"name": "accelerate", "version": "1.12.0"},
            {"name": "peft", "version": "0.18.1"},
            {"name": "trl", "version": "0.24.0"},
            {"name": "deepspeed", "version": "0.18.9"},
            {"name": "flash-attn", "version": "2.8.3"},
            {"name": "triton", "version": "3.6.0"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/odh-th06-cuda130-torch210-py312
      from:
        kind: DockerImage
        name: quay.io/opendatahub/odh-th06-cuda130-torch210-py312:odh-3.4
      referencePolicy:
        type: Source
    - name: "3.5"
      annotations:
        opendatahub.io/workbench-image-recommended: 'true'
        opendatahub.io/notebook-build-commit: a66ec72
        opendatahub.io/notebook-software: |
          [
            {"name": "CUDA", "version": "13.0"},
            {"name": "Python", "version": "v3.12"},
            {"name": "PyTorch", "version": "2.10.0"},
            {"name": "Training Hub", "version": "v0.6.0"}
          ]
        opendatahub.io/notebook-python-dependencies: |
          [
            {"name": "transformers", "version": "4.57.6"},
            {"name": "accelerate", "version": "1.12.0"},
            {"name": "peft", "version": "0.18.1"},
            {"name": "trl", "version": "0.24.0"},
            {"name": "deepspeed", "version": "0.18.9"},
            {"name": "flash-attn", "version": "2.8.3"},
            {"name": "triton", "version": "3.6.0"}
          ]
        openshift.io/imported-from: quay.io/opendatahub/odh-th06-cuda130-torch210-py312
      from:
        kind: DockerImage
        name: quay.io/opendatahub/odh-th06-cuda130-torch210-py312:odh-3.5-ea1
      referencePolicy:
        type: Source
